const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const read = relativePath =>
  fs.readFileSync(path.join(root, relativePath), 'utf8')

const {
  resolveTheme,
  nextTheme,
  tagsMatch
} = require('../source/js/notebook.js')

test('theme resolution follows saved choice before system choice', () => {
  assert.equal(resolveTheme('dark', false), 'dark')
  assert.equal(resolveTheme('light', true), 'light')
  assert.equal(resolveTheme(null, true), 'dark')
  assert.equal(resolveTheme(null, false), 'light')
  assert.equal(nextTheme('dark'), 'light')
  assert.equal(nextTheme('light'), 'dark')
})

test('project tag matching supports all and comma-delimited tags', () => {
  assert.equal(tagsMatch('all', 'React,TypeScript'), true)
  assert.equal(tagsMatch('React', 'React,TypeScript'), true)
  assert.equal(tagsMatch('Go', 'React,TypeScript'), false)
})

test('notebook data and original assets define the approved navigation', () => {
  const data = read('source/_data/notebook.yml')
  assert.match(data, /role: "Independent Developer · Writer"/)
  for (const id of ['projects', 'writing', 'notes', 'about', 'github', 'contact']) {
    assert.match(data, new RegExp(`id: ${id}`))
  }

  const wordmark = read('source/img/notebook/wordmark.svg')
  const icons = read('source/img/notebook/icons.svg')
  assert.match(wordmark, /aria-labelledby="wordmark-title"/)
  assert.match(icons, /<symbol id="icon-projects"/)
  assert.match(icons, /<symbol id="icon-contact"/)
})

test('approved RSS footer target is generated by Hexo', () => {
  const packageJson = JSON.parse(read('package.json'))
  assert.ok(packageJson.devDependencies['hexo-generator-feed'])
  assert.match(read('_config.yml'), /feed:\s*\n\s+type:\s+atom\s*\n\s+path:\s+atom\.xml/)
})

test('theme stylesheet contains both palettes and reduced-motion rules', () => {
  const css = read('source/css/notebook.css')
  assert.match(css, /--notebook-canvas:\s*#ecebeb/i)
  assert.match(css, /\[data-theme="dark"\]/)
  assert.match(css, /--notebook-paper:\s*#242225/i)
  assert.match(css, /prefers-reduced-motion:\s*reduce/)
  assert.match(css, /min-height:\s*44px/)
})
