const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const read = relativePath =>
  fs.readFileSync(path.join(root, relativePath), 'utf8')

const {
  resolveTheme,
  nextTheme,
  tagsMatch
} = require('../source/js/notebook.js')

test('theme resolution follows saved choice before system choice', () => {
  assert.equal(resolveTheme('dark', false), 'dark')
  assert.equal(resolveTheme('light', true), 'light')
  assert.equal(resolveTheme(null, true), 'dark')
  assert.equal(resolveTheme(null, false), 'light')
  assert.equal(nextTheme('dark'), 'light')
  assert.equal(nextTheme('light'), 'dark')
})

test('project tag matching supports all and comma-delimited tags', () => {
  assert.equal(tagsMatch('all', 'React,TypeScript'), true)
  assert.equal(tagsMatch('React', 'React,TypeScript'), true)
  assert.equal(tagsMatch('Go', 'React,TypeScript'), false)
})

test('notebook data defines five configurable Pokemon destinations', () => {
  const data = read('source/_data/notebook.yml')
  const expected = {
    projects: '/img/pokemon/pikachu.png',
    writing: '/img/pokemon/psyduck.png',
    about: '/img/pokemon/eevee.png',
    github: '/img/pokemon/meowth.png',
    contact: '/img/pokemon/jigglypuff.png'
  }

  for (const [id, icon] of Object.entries(expected)) {
    assert.match(data, new RegExp(`id: ${id}[^\\n]*icon: ${icon.replaceAll('/', '\\/')}`))
    const bytes = fs.readFileSync(path.join(root, 'source', icon))
    assert.equal(bytes.subarray(1, 4).toString('ascii'), 'PNG')
  }

  assert.doesNotMatch(data, /id: notes/)
  assert.doesNotMatch(data, /label: 随记/)
})

test('notebook fallback SVG assets remain available', () => {
  const wordmark = read('source/img/notebook/wordmark.svg')
  const icons = read('source/img/notebook/icons.svg')
  assert.match(wordmark, /aria-labelledby="wordmark-title"/)
  assert.match(icons, /<symbol id="icon-projects"/)
  assert.match(icons, /<symbol id="icon-contact"/)
})

test('approved RSS footer target is generated by Hexo', () => {
  const packageJson = JSON.parse(read('package.json'))
  assert.ok(packageJson.devDependencies['hexo-generator-feed'])
  assert.match(read('_config.yml'), /feed:\s*\n\s+type:\s+atom\s*\n\s+path:\s+atom\.xml/)
})

test('documented local preview command has its Hexo server dependency', () => {
  const packageJson = JSON.parse(read('package.json'))
  assert.ok(packageJson.devDependencies['hexo-server'])
})

test('Butterfly rightside handlers tolerate the notebook shell omitting rightside', () => {
  const script = read('themes/butterfly/source/js/main.js')
  assert.match(
    script,
    /const \$rightside = document\.getElementById\('rightside'\)\s+if \(!\$rightside\) return/
  )
  assert.match(
    script,
    /document\.getElementById\('rightside'\)\?\.addEventListener\('click'/
  )
})

test('Butterfly menu adjustment tolerates the notebook shell omitting menus', () => {
  const script = read('themes/butterfly/source/js/main.js')
  assert.match(
    script,
    /const adjustMenu = init => \{\s+if \(!document\.getElementById\('menus'\)\) return/
  )
  assert.match(
    script,
    /adjustMenu\(true\)\s+\$nav\?\.classList\.add\('show'\)/
  )
})

test('outdate notice preserves post content in the notebook reading shell', () => {
  const template = read('themes/butterfly/layout/post.pug')
  assert.match(
    template,
    /^ {6}if theme\.noticeOutdate\.enable && page\.noticeOutdate !== false\r?\n {8}include includes\/post\/outdate-notice\.pug\r?\n {6}!=page\.content$/m
  )
  assert.doesNotMatch(
    template,
    /include includes\/post\/outdate-notice\.pug\s+else\s+!=page\.content/
  )
})

test('theme stylesheet contains both palettes and reduced-motion rules', () => {
  const css = read('source/css/notebook.css')
  assert.match(css, /--notebook-canvas:\s*#ecebeb/i)
  assert.match(css, /\[data-theme="dark"\]/)
  assert.match(css, /--notebook-paper:\s*#242225/i)
  assert.match(css, /prefers-reduced-motion:\s*reduce/)
})

test('reduced-motion mode removes destination hover movement', () => {
  const css = read('source/css/notebook.css')
  assert.match(
    css,
    /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.notebook-site \.notebook-destination:hover\s*\{[^}]*transform:\s*none;/
  )
})

test('all interactive notebook controls meet the minimum target size', () => {
  const css = read('source/css/notebook.css')
  for (const selector of [
    '.notebook-site .notebook-theme-toggle',
    '.notebook-site .notebook-tab',
    '.notebook-site .notebook-destination',
    '.notebook-site .notebook-footer-links a'
  ]) {
    const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const rule = new RegExp(
      `${escapedSelector}[^}]*min-width:\\s*44px;[^}]*min-height:\\s*44px;`
    )
    assert.match(css, rule, `${selector} must provide a 44px minimum target`)
  }
})

test('homepage template renders configured images with an SVG fallback', () => {
  const template = read('themes/butterfly/layout/notebook-home.pug')
  assert.match(template, /if item\.icon/)
  assert.match(template, /img\.notebook-destination__image\(src=url_for\(item\.icon\) alt=item\.label\)/)
  assert.match(template, /else\s+\+notebookIcon\(item\.id, item\.label\)/)
})

test('generated homepage is a five-destination Pokemon notebook index', () => {
  const html = read('public/index.html')
  assert.match(html, /class="notebook-site notebook-home"/)
  assert.match(html, /data-theme-toggle/)
  assert.match(html, /aria-label="主要入口"/)
  const expected = {
    projects: 'pikachu.png',
    writing: 'psyduck.png',
    about: 'eevee.png',
    github: 'meowth.png',
    contact: 'jigglypuff.png'
  }

  for (const [id, filename] of Object.entries(expected)) {
    assert.match(html, new RegExp(`data-destination="${id}"[\\s\\S]*?img/pokemon/${filename}`))
  }

  assert.doesNotMatch(html, /data-destination="notes"/)
  assert.equal((html.match(/data-destination=/g) || []).length, 5)
  assert.equal((html.match(/class="notebook-destination__image"/g) || []).length, 5)
})

test('projects page uses shared shell and renders project data', () => {
  const html = read('public/projects/index.html')
  const projectCount = (read('source/_data/projects.yml').match(/^- name:/gm) || []).length
  assert.match(html, /class="notebook-header"/)
  assert.match(html, /aria-current="page"[^>]*>作品</)
  assert.match(html, /data-project-filter="all"/)
  assert.match(html, /data-project-status/)
  assert.equal(
    (html.match(/data-project-tags=/g) || []).length,
    projectCount
  )
})

test('about page renders approved notes in semantic order', () => {
  const html = read('public/about/index.html')
  assert.match(html, /class="notebook-about-notes"/)
  for (const title of ['Hello', '正在做', '常用工具', '兴趣', '联系我']) {
    assert.match(html, new RegExp(title))
  }
  assert.match(html, /class="notebook-footer"/)
})

test('archive is a compact chronological notebook list', () => {
  const html = read('public/archives/index.html')
  assert.match(html, /class="notebook-archive"/)
  assert.match(html, /class="notebook-archive-item"/)
  assert.match(html, /aria-current="page"[^>]*>文章</)
})

test('post pages keep article content inside the notebook reading shell', () => {
  const html = read('public/posts/github-pages-deploy/index.html')
  assert.match(html, /class="notebook-post"/)
  assert.match(html, /class="[^"]*notebook-reading[^"]*"/)
  assert.match(html, /GitHub Pages 部署指南/)
  assert.match(html, /<pre/)
})

test('generated core pages expose skip links and labeled theme controls', () => {
  for (const relativePath of [
    'public/index.html',
    'public/projects/index.html',
    'public/about/index.html',
    'public/archives/index.html'
  ]) {
    const html = read(relativePath)
    assert.match(html, /跳到主内容/)
    assert.match(html, /data-theme-toggle/)
    assert.match(html, /aria-label="切换到(浅色|暗色)主题"/)
  }
})

test('Pokemon destinations use open desktop and centered mobile layouts', () => {
  const css = read('source/css/notebook.css')
  assert.match(css, /grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*78px\)\)/)
  assert.match(css, /column-gap:\s*36px/)
  assert.match(css, /row-gap:\s*28px/)
  assert.match(css, /\.notebook-destination:nth-child\(4\)[^{]*\{[^}]*grid-column:\s*2\s*\/\s*span 2/)
  assert.match(css, /\.notebook-destination:nth-child\(5\)[^{]*\{[^}]*grid-column:\s*4\s*\/\s*span 2/)
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.notebook-cover \.notebook-destination:nth-child\(4\)[^{]*\{[^}]*grid-column:\s*auto/)
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.notebook-destination:nth-child\(5\)[^{]*\{[^}]*grid-column:\s*1\s*\/\s*-1/)
  assert.match(css, /@media \(max-width:\s*359px\)[\s\S]*grid-template-columns:\s*1fr/)
  assert.match(css, /\.notebook-destination__image[^{]*\{[^}]*flex:\s*0\s+0\s+auto/)
})
