const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const read = relativePath =>
  fs.readFileSync(path.join(root, relativePath), 'utf8')

const {
  resolveTheme,
  nextTheme,
  tagsMatch
} = require('../source/js/notebook.js')

test('theme resolution follows saved choice before system choice', () => {
  assert.equal(resolveTheme('dark', false), 'dark')
  assert.equal(resolveTheme('light', true), 'light')
  assert.equal(resolveTheme(null, true), 'dark')
  assert.equal(resolveTheme(null, false), 'light')
  assert.equal(nextTheme('dark'), 'light')
  assert.equal(nextTheme('light'), 'dark')
})

test('project tag matching supports all and comma-delimited tags', () => {
  assert.equal(tagsMatch('all', 'React,TypeScript'), true)
  assert.equal(tagsMatch('React', 'React,TypeScript'), true)
  assert.equal(tagsMatch('Go', 'React,TypeScript'), false)
})

test('notebook data defines five configurable Pokemon destinations', () => {
  const data = read('source/_data/notebook.yml')
  const expected = {
    projects: '/img/pokemon/pikachu.png',
    writing: '/img/pokemon/psyduck.png',
    about: '/img/pokemon/eevee.png',
    github: '/img/pokemon/meowth.png',
    contact: '/img/pokemon/jigglypuff.png'
  }

  for (const [id, icon] of Object.entries(expected)) {
    assert.match(data, new RegExp(`id: ${id}[^\\n]*icon: ${icon.replaceAll('/', '\\/')}`))
    const bytes = fs.readFileSync(path.join(root, 'source', icon))
    assert.equal(bytes.subarray(1, 4).toString('ascii'), 'PNG')
  }

  assert.doesNotMatch(data, /id: notes/)
  assert.doesNotMatch(data, /label: 随记/)
})

test('wordmark provides accessible light and dark SVG variants', () => {
  const wordmark = read('source/img/notebook/wordmark.svg')
  const darkWordmark = read('source/img/notebook/wordmark-dark.svg')
  const icons = read('source/img/notebook/icons.svg')
  assert.match(wordmark, /aria-labelledby="wordmark-title"/)
  assert.match(wordmark, /fill="#171717"/)
  assert.match(darkWordmark, /aria-labelledby="wordmark-title"/)
  assert.match(darkWordmark, /fill="#f4f1f3"/)
  assert.match(darkWordmark, /stroke="#ef4f98"/)
  assert.match(icons, /<symbol id="icon-projects"/)
  assert.match(icons, /<symbol id="icon-contact"/)

  for (const templatePath of [
    'components/site-header/template.pug',
    'components/home-header/template.pug',
    'themes/butterfly/layout/includes/notebook/header.pug'
  ]) {
    const template = read(templatePath)
    assert.match(template, /notebook-wordmark__image--light/)
    assert.match(template, /notebook-wordmark__image--dark/)
  }

  const css = read('source/css/notebook.css')
  assert.match(css, /\.notebook-wordmark__image--dark\s*\{[^}]*display:\s*none;/)
  assert.match(css, /\[data-theme="dark"\][\s\S]*?\.notebook-wordmark__image--dark\s*\{[^}]*display:\s*block;/)
})

test('approved RSS footer target is generated by Hexo', () => {
  const packageJson = JSON.parse(read('package.json'))
  assert.ok(packageJson.devDependencies['hexo-generator-feed'])
  assert.match(read('_config.yml'), /feed:\s*\n\s+type:\s+atom\s*\n\s+path:\s+atom\.xml/)
})

test('documented local preview command has its Hexo server dependency', () => {
  const packageJson = JSON.parse(read('package.json'))
  assert.ok(packageJson.devDependencies['hexo-server'])
})

test('Butterfly rightside handlers tolerate the notebook shell omitting rightside', () => {
  const script = read('themes/butterfly/source/js/main.js')
  assert.match(
    script,
    /const \$rightside = document\.getElementById\('rightside'\)\s+if \(!\$rightside\) return/
  )
  assert.match(
    script,
    /document\.getElementById\('rightside'\)\?\.addEventListener\('click'/
  )
})

test('Butterfly menu adjustment tolerates the notebook shell omitting menus', () => {
  const script = read('themes/butterfly/source/js/main.js')
  assert.match(
    script,
    /const adjustMenu = init => \{\s+if \(!document\.getElementById\('menus'\)\) return/
  )
  assert.match(
    script,
    /adjustMenu\(true\)\s+\$nav\?\.classList\.add\('show'\)/
  )
})

test('outdate notice preserves post content in the notebook reading shell', () => {
  const template = read('themes/butterfly/layout/post.pug')
  assert.match(
    template,
    /^ {6}if theme\.noticeOutdate\.enable && page\.noticeOutdate !== false\r?\n {8}include includes\/post\/outdate-notice\.pug\r?\n {6}!=page\.content$/m
  )
  assert.doesNotMatch(
    template,
    /include includes\/post\/outdate-notice\.pug\s+else\s+!=page\.content/
  )
})

test('theme stylesheet contains both palettes and reduced-motion rules', () => {
  const css = read('source/css/notebook.css')
  assert.match(css, /--notebook-canvas:\s*#ecebeb/i)
  assert.match(css, /\[data-theme="dark"\]/)
  assert.match(css, /--notebook-paper:\s*#242225/i)
  assert.match(css, /--notebook-grid:\s*rgba\(212,\s*203,\s*211,\s*0\.24\)/)
  assert.match(css, /--notebook-grid:\s*rgba\(255,\s*255,\s*255,\s*0\.04\)/)
  assert.match(css, /prefers-reduced-motion:\s*reduce/)
})

test('inner-page type hierarchy keeps headings compact and roles distinct', () => {
  const css = read('source/css/notebook.css')
  assert.match(css, /--notebook-type-page:\s*clamp\(2\.5rem,\s*5vw,\s*4\.5rem\)/)
  assert.match(css, /--notebook-type-meta:\s*0\.8125rem/)
  assert.match(css, /--notebook-type-meta-spacing:\s*0\.08em/)
  assert.match(
    css,
    /\.notebook-site \.notebook-page-heading h1\s*\{[\s\S]*?font-size:\s*var\(--notebook-type-page\);/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-post#post > #post-info\s*\{[\s\S]*?width:\s*min\(100%,\s*760px\);[\s\S]*?margin:\s*0 auto clamp\(20px,\s*4vw,\s*32px\);/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-post#post > #post-info \.post-title\s*\{[\s\S]*?padding:\s*0;[\s\S]*?border-bottom:\s*0;[\s\S]*?font-size:\s*var\(--notebook-type-post\);[\s\S]*?line-height:\s*1\.14;/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-project__body h2\s*\{[\s\S]*?font-size:\s*var\(--notebook-type-card\);[\s\S]*?line-height:\s*1\.3;/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-note-title\s*\{[\s\S]*?font-size:\s*var\(--notebook-type-card\);[\s\S]*?line-height:\s*1\.3;/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-archive > \.article-sort-title\s*\{[\s\S]*?margin-left:\s*0;[\s\S]*?font-size:\s*var\(--notebook-type-section\);/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-kicker,[\s\S]*?\.notebook-site \.notebook-project__eyebrow\s*\{[\s\S]*?font-size:\s*var\(--notebook-type-meta\);[\s\S]*?font-weight:\s*var\(--notebook-type-meta-weight\);[\s\S]*?letter-spacing:\s*var\(--notebook-type-meta-spacing\);/
  )
})

test('navigation separates hover feedback from the current-page state', () => {
  const css = read('source/css/notebook.css')
  assert.doesNotMatch(css, /\.notebook-tab:hover,\s*\.notebook-tab\[aria-current="page"\]/)
  assert.match(
    css,
    /\.notebook-site \.notebook-tab\[aria-current="page"\]\s*\{[\s\S]*?background:\s*color-mix\(in srgb, var\(--notebook-pink\) 12%, var\(--notebook-paper\)\);[\s\S]*?box-shadow:\s*inset 0 -2px 0 var\(--notebook-pink\);/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-tab:hover,[\s\S]*?\.notebook-site \.notebook-theme-toggle:hover\s*\{[\s\S]*?background:\s*var\(--notebook-paper\);/
  )
})

test('notebook stylesheet cache version is consistent across shell entry points', () => {
  for (const sourcePath of [
    '_config.butterfly.yml',
    'themes/butterfly/layout/notebook-home.pug'
  ]) {
    assert.match(read(sourcePath), /notebook\.css\?v=8/)
  }
})

test('reduced-motion mode removes destination hover movement', () => {
  const css = read('source/css/notebook.css')
  assert.match(
    css,
    /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.notebook-site \.notebook-destination:hover\s*\{[^}]*transform:\s*none;/
  )
})

test('all interactive notebook controls meet the minimum target size', () => {
  const css = read('source/css/notebook.css')
  for (const selector of [
    '.notebook-site .notebook-theme-toggle',
    '.notebook-site .notebook-tab',
    '.notebook-site .notebook-destination',
    '.notebook-site .notebook-footer-links a'
  ]) {
    const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const rule = new RegExp(
      `${escapedSelector}[^}]*min-width:\\s*44px;[^}]*min-height:\\s*44px;`
    )
    assert.match(css, rule, `${selector} must provide a 44px minimum target`)
  }
})

test('destination-grid component renders configured images with an SVG fallback', () => {
  const template = read('components/destination-grid/template.pug')
  assert.match(template, /if item\.icon/)
  assert.match(template, /img\.notebook-destination__image\(src=url_for\(item\.icon\) alt=""\)/)
  assert.match(template, /svg\.notebook-icon\(role="img" aria-label=item\.label\)/)
  assert.match(template, /use\(href=url_for\(`\/img\/notebook\/icons\.svg#icon-\$\{item\.id\}`\)\)/)
})

test('generated homepage is a five-destination Pokemon notebook index', () => {
  const html = read('public/index.html')
  assert.match(html, /class="notebook-site notebook-home"/)
  assert.match(html, /data-theme-toggle/)
  assert.match(html, /aria-label="主要入口"/)
  const expected = {
    projects: 'pikachu.png',
    writing: 'psyduck.png',
    about: 'eevee.png',
    github: 'meowth.png',
    contact: 'jigglypuff.png'
  }

  for (const [id, filename] of Object.entries(expected)) {
    assert.match(html, new RegExp(`data-destination="${id}"[\\s\\S]*?img/pokemon/${filename}`))
  }

  assert.doesNotMatch(html, /data-destination="notes"/)
  assert.equal((html.match(/data-destination=/g) || []).length, 5)
  assert.equal((html.match(/class="notebook-destination__image"/g) || []).length, 5)
  assert.equal((html.match(/class="notebook-destination__image"[^>]*alt=""/g) || []).length, 5)
})

test('generated homepage exposes complete social metadata and structured identity', () => {
  const html = read('public/index.html')
  const homeUrl = 'https://biubiutoo.cn/'
  const homeImage = `${homeUrl}img/favicon-512.png`

  assert.match(html, new RegExp(`<link rel="canonical" href="${homeUrl}">`))
  assert.match(html, /<meta property="og:type" content="website">/)
  assert.match(html, new RegExp(`<meta property="og:url" content="${homeUrl}">`))
  assert.match(html, new RegExp(`<meta property="og:image" content="${homeImage}">`))
  assert.match(html, /<meta name="twitter:card" content="summary">/)
  assert.match(html, new RegExp(`<meta name="twitter:image" content="${homeImage}">`))
  assert.equal((html.match(/<h1\b/g) || []).length, 1)
  assert.match(html, /<h1 class="notebook-sr-only" id="home-title">凌云 · 独立开发者<\/h1>/)

  const jsonLd = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)
  assert.ok(jsonLd, 'homepage must include JSON-LD')
  const data = JSON.parse(jsonLd[1])
  assert.equal(data['@context'], 'https://schema.org')
  assert.deepEqual(data['@graph'].map(item => item['@type']), ['WebSite', 'Person', 'ProfilePage'])
  assert.equal(data['@graph'][1].url, homeUrl)
  assert.deepEqual(data['@graph'][1].sameAs, ['https://github.com/LingyunAce'])
})

test('single-project page uses a featured case-study layout without filters', () => {
  const html = read('public/projects/index.html')
  const template = read('components/project-gallery/template.pug')
  const projectCount = (read('source/_data/projects.yml').match(/^- name:/gm) || []).length
  assert.match(html, /class="notebook-header"/)
  assert.match(html, /aria-current="page"[^>]*>作品</)
  assert.match(template, /projects\.length >= 4/)
  assert.match(template, /data-project-filter/)
  if (projectCount === 1) {
    assert.match(html, /notebook-project-grid--featured/)
    assert.match(html, /notebook-project--featured/)
    assert.match(html, /notebook-project__cta/)
    assert.doesNotMatch(html, /data-project-filter=/)
    assert.doesNotMatch(html, /data-project-status/)
  } else if (projectCount >= 4) {
    assert.match(html, /data-project-filter="all"/)
    assert.match(html, /data-project-status/)
  } else {
    assert.doesNotMatch(html, /data-project-filter=/)
    assert.doesNotMatch(html, /data-project-status/)
  }
  assert.equal(
    (html.match(/data-project-tags=/g) || []).length,
    projectCount
  )
})

test('mobile notebook header uses two rows with a horizontally scrollable nav', () => {
  const css = read('source/css/notebook.css')
  assert.match(
    css,
    /@media \(max-width:\s*600px\)[\s\S]*?\.notebook-site \.notebook-header-inner\s*\{[\s\S]*?grid-template-areas:[\s\S]*?"brand actions"[\s\S]*?"nav nav"/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-header-inner \.notebook-tabs\s*\{[\s\S]*?overflow-x:\s*auto;[\s\S]*?flex-wrap:\s*nowrap;/
  )
  assert.match(
    css,
    /\.notebook-site \.notebook-header-inner \.notebook-wordmark\s*\{[\s\S]*?width:\s*min\(210px,\s*56vw\)/
  )
})

test('about page renders approved notes in semantic order', () => {
  const html = read('public/about/index.html')
  assert.match(html, /class="notebook-about-notes"/)
  for (const title of ['Hello', '正在做', '常用工具', '兴趣', '联系我']) {
    assert.match(html, new RegExp(title))
  }
  assert.match(html, /class="notebook-footer"/)
})

test('archive is a compact chronological notebook list', () => {
  const html = read('public/archives/index.html')
  const css = read('source/css/notebook.css')
  assert.match(html, /class="notebook-archive"/)
  assert.match(html, /class="notebook-archive-item"/)
  assert.match(html, /aria-current="page"[^>]*>文章</)
  assert.equal((html.match(/<h1\b/g) || []).length, 1)
  assert.match(html, /<h1 class="article-sort-title">全部文章 - \d+<\/h1>/)
  assert.match(html, /<meta name="description" content="按时间浏览凌云的技术文章、项目实践与日常思考。">/)
  assert.match(
    css,
    /\.notebook-site \.notebook-archive > \.article-sort-title\s*\{[^}]*margin-left:\s*0;/
  )
})

test('post pages keep article content inside the notebook reading shell', () => {
  const html = read('public/posts/github-pages-deploy/index.html')
  assert.match(html, /class="notebook-post"/)
  assert.match(html, /class="[^"]*notebook-reading[^"]*"/)
  assert.match(html, /aria-current="page"[^>]*>文章</)
  assert.match(html, /GitHub Pages 部署指南/)
  assert.match(html, /<pre/)
})

test('generated core pages expose skip links and labeled theme controls', () => {
  for (const relativePath of [
    'public/index.html',
    'public/projects/index.html',
    'public/about/index.html',
    'public/archives/index.html'
  ]) {
    const html = read(relativePath)
    assert.match(html, /跳到主内容/)
    assert.match(html, /data-theme-toggle/)
    assert.match(html, /aria-label="切换到(浅色|暗色)主题"/)
  }
})

test('Pokemon destinations use open desktop and centered mobile layouts', () => {
  const css = read('source/css/notebook.css')
  assert.match(css, /grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*78px\)\)/)
  assert.match(css, /column-gap:\s*36px/)
  assert.match(css, /row-gap:\s*28px/)
  assert.match(css, /\.notebook-destination:nth-child\(4\)[^{]*\{[^}]*grid-column:\s*2\s*\/\s*span 2/)
  assert.match(css, /\.notebook-destination:nth-child\(5\)[^{]*\{[^}]*grid-column:\s*4\s*\/\s*span 2/)
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.notebook-cover \.notebook-destination:nth-child\(4\)[^{]*\{[^}]*grid-column:\s*auto/)
  assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*\.notebook-destination:nth-child\(5\)[^{]*\{[^}]*grid-column:\s*1\s*\/\s*-1/)
  assert.match(css, /@media \(max-width:\s*359px\)[\s\S]*grid-template-columns:\s*1fr/)
  assert.match(css, /\.notebook-destination__image[^{]*\{[^}]*flex:\s*0\s+0\s+auto/)
})

test('every configured component ships a manifest and template', () => {
  const configYaml = read('source/_data/components.yml')
  const ids = new Set()
  const re = new RegExp('component:\\s*(\\S+)', 'g')
  let m
  while ((m = re.exec(configYaml)) !== null) ids.add(m[1])
  assert.ok(ids.size >= 9)
  for (const id of ids) {
    const manifest = read(`components/${id}/component.yml`)
    assert.match(manifest, new RegExp(`id:\\s*${id}`))
    assert.ok(read(`components/${id}/template.pug`).length > 0, `${id} 必须有 template.pug`)
  }
})

test('component asset bundles are generated alongside core pages', () => {
  const css = read('public/css/components.css')
  const js = read('public/js/components.js')
  assert.ok(typeof css === 'string')
  assert.ok(typeof js === 'string')
})
